name = "points-redemption-dashboard"
compatibility_date = "2026-06-16"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "points-redemption-dashboard"
database_id = "cf67f42f-f49b-4169-9710-5c03a4b26158"
migrations_dir = "migrations"
